name: YouTube Upload

on:
  schedule:
    - cron: '50 2 * * *' # 매일 11:50 KST (UTC+9 → UTC 02:50)
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install -r youtube_uploader/requirements_youtube.txt
     
      - name: Restore client_secrets.json
        run: echo "${{ secrets.YOUTUBE_CLIENT_SECRETS }}" > youtube_uploader/client_secrets.json

      - name: Restore token.json
        run: printf "%s" '${{ secrets.YOUTUBE_TOKEN_JSON }}' > youtube_uploader/token.json
  
      - name: Check token.json content
        run: cat youtube_uploader/token.json
      
      - name: Upload to YouTube
        run: python youtube_uploader/upload_to_youtube.py


